#!/usr/bin/env php
<?php ini_set('display_errors', false);

echo "Initializing ...\n";

require 'src/functions.php';
require 'src/gamedata.php';

echo "Enter a command: ";

switch (trim(fgets(STDIN))) {
    case 'badges':
        require 'src/badges.php';
        break;
    case 'furnitures':
        require 'src/furnitures.php';
        break;
    case 'clothes':
        require 'src/clothes.php';
        break;
    case 'icons':
        require 'src/icons.php';
        break;
    case 'mp3':
        require 'src/mp3.php';
        break;
    default:
        exit;
}
